In [1]:
import numpy as np
array=np.array([3,33,333])
print type(array)

<type 'numpy.ndarray'>


In [2]:
print array.shape

(3,)


In [3]:
print array[0], array[1], array[2]

3 33 333


In [4]:
array[0]=888
print array

[888  33 333]


We can change type of element in array

In [7]:
another=np.array([[1,2,3], [8, 11, 15]])
print type(another)


<type 'numpy.ndarray'>


In [8]:
print another.shape, another[0][1]

(2, 3) 2


In [14]:
#create 2x2 matrix of zero
zeros=np.zeros([2,2])
print zeros

[[ 0.  0.]
 [ 0.  0.]]


In [16]:
#create 2x2 matrix of 9.0
nines=np.full([2,2],9.0)
print nines

[[ 9.  9.]
 [ 9.  9.]]


In [18]:
#create matrix diagonal 1 and other 0
diagol=np.eye(3,3)
print diagol

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [20]:
#create matrix ones
ones=np.ones([1,3])
print ones

[[ 1.  1.  1.]]


In [21]:
#create matrix random between 0, 1
randoms=np.random.random([2,2])
print randoms

[[ 0.1903442   0.29152745]
 [ 0.33114719  0.40399547]]
